# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import hltv_pb2 as hltv__pb2

GRPC_GENERATED_VERSION = '1.66.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in hltv_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HltvServiceStub(object):
    """---- Service ----

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SyncTeams = channel.unary_unary(
                '/home_calendar.hltv.HltvService/SyncTeams',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=hltv__pb2.SyncTeamsResponse.FromString,
                _registered_method=True)
        self.SyncMatches = channel.unary_unary(
                '/home_calendar.hltv.HltvService/SyncMatches',
                request_serializer=hltv__pb2.SyncMatchesRequest.SerializeToString,
                response_deserializer=hltv__pb2.SyncMatchesResponse.FromString,
                _registered_method=True)


class HltvServiceServicer(object):
    """---- Service ----

    """

    def SyncTeams(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncMatches(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HltvServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SyncTeams': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncTeams,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=hltv__pb2.SyncTeamsResponse.SerializeToString,
            ),
            'SyncMatches': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncMatches,
                    request_deserializer=hltv__pb2.SyncMatchesRequest.FromString,
                    response_serializer=hltv__pb2.SyncMatchesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'home_calendar.hltv.HltvService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('home_calendar.hltv.HltvService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HltvService(object):
    """---- Service ----

    """

    @staticmethod
    def SyncTeams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/home_calendar.hltv.HltvService/SyncTeams',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            hltv__pb2.SyncTeamsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncMatches(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/home_calendar.hltv.HltvService/SyncMatches',
            hltv__pb2.SyncMatchesRequest.SerializeToString,
            hltv__pb2.SyncMatchesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
